name: Suggestion/Feature Request
description: Suggest an idea for the project.
title: "[Suggestion]: Title here"
labels: ["enhancement"]

body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: If yes, provide a clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Feature Description
      description: Provide a clear and detailed description of your feature suggestion.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Windows version 
      description: | 
        *You can find this in `About your PC` in settings under `Windows specifications`*
      options:
        - Windows 11 (22H2)
        - Windows 11 (21H2)
        - Windows 10 (22H2)
        - Windows 10 (21H2)
        - Windows 10 (other/earlier)
        - Windows 11 (23H2)
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the suggestion here.
    validations:
      required: false
